# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r: release
 r_packages:
   - pkgdown
 env: R_CURRENT=true
 deploy:
   provider: script
   script:
     R CMD build . && Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE, tarball = ".")'
cleanup: true

after_success:
  - Rscript -e 'covr::codecov()'
